<TestScreen>:
    MDLabel:
        id: contents
        pos_hint: {"center_x": 0.5, "center_y": 0.9}
        halign:  "center"
        size_hint_x: 0.8
        text: "?"

    Answer:
        letter: "a"
        id: answer_a
        pos_hint: {"x": 0.2, "center_y": 0.7}
    Answer:
        letter: "b"
        id: answer_b
        pos_hint: {"x": 0.2, "center_y": 0.6}
    Answer:
        letter: "c"
        id: answer_c
        pos_hint: {"x": 0.2, "center_y": 0.5}
    Answer:
        letter: "d"
        id: answer_d
        pos_hint: {"x": 0.2, "center_y": 0.4}
    Answer:
        letter: "e"
        id: answer_e
        pos_hint: {"x": 0.2, "center_y": 0.3}

    MDRectangleFlatButton:
        id: check
        pos_hint: {"center_x": 0.2, "center_y": 0.2}
        text: "Check answer"
        on_press: root.check_answer()

    MDRectangleFlatButton:
        id: check
        pos_hint: {"center_x": 0.4, "center_y": 0.2}
        text: "Clear selection"
        on_press: root.clear_selection()

    MDRectangleFlatButton:
        id: clear
        pos_hint: {"center_x": 0.6, "center_y": 0.2}
        text: "Shuffle answers"
        on_press: root.update_labels()

    MDRectangleFlatButton:
        id: next
        pos_hint: {"center_x": 0.8, "center_y": 0.2}
        text: "Next question"
        on_press: root.next_question()

    MDRectangleFlatButton:
        id: exit
        pos_hint: {"center_x": 0.5, "center_y": 0.1}
        text: "Exit"
        on_press: app.root.ids.screen_manager.current = "main"



